<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>cam_pub</name>
  <version>0.0.1</version>
  <description>This package was created as part of the technical challenge for the Robotics Systems Engineer position at Rapyuta Robotics. The goal is to develop a simple object-tracking system using a webcam.</description>
  <maintainer email="gilmarcorreiajeronimo@gmail.com">Gilmar Correia Jeronimo</maintainer>
  <license>BSD-2-Clause</license>

  <buildtool_depend>ament_cmake</buildtool_depend>
  <build_depend>cv_bridge</build_depend>
  <build_depend>image_transport</build_depend>

  <depend>rclcpp</depend>
  <depend>sensor_msgs</depend>
  <depend>challenge_interfaces</depend>
  
  <exec_depend>cv_bridge</exec_depend>
  <exec_depend>image_transport</exec_depend>

  <test_depend>ament_lint_auto</test_depend>
  <test_depend>ament_lint_common</test_depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
